// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: server/plugin/plg_handler_grpc_session/pb/sidecar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessMode int32

const (
	AccessMode_ACCESS_MODE_UNSPECIFIED AccessMode = 0
	AccessMode_ACCESS_MODE_READ        AccessMode = 1
	AccessMode_ACCESS_MODE_READ_WRITE  AccessMode = 2
)

// Enum value maps for AccessMode.
var (
	AccessMode_name = map[int32]string{
		0: "ACCESS_MODE_UNSPECIFIED",
		1: "ACCESS_MODE_READ",
		2: "ACCESS_MODE_READ_WRITE",
	}
	AccessMode_value = map[string]int32{
		"ACCESS_MODE_UNSPECIFIED": 0,
		"ACCESS_MODE_READ":        1,
		"ACCESS_MODE_READ_WRITE":  2,
	}
)

func (x AccessMode) Enum() *AccessMode {
	p := new(AccessMode)
	*p = x
	return p
}

func (x AccessMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessMode) Descriptor() protoreflect.EnumDescriptor {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_enumTypes[0].Descriptor()
}

func (AccessMode) Type() protoreflect.EnumType {
	return &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_enumTypes[0]
}

func (x AccessMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessMode.Descriptor instead.
func (AccessMode) EnumDescriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{0}
}

type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	SessionState_SESSION_STATE_ACTIVE      SessionState = 1
	SessionState_SESSION_STATE_CLOSED      SessionState = 2
	SessionState_SESSION_STATE_EXPIRED     SessionState = 3
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_ACTIVE",
		2: "SESSION_STATE_CLOSED",
		3: "SESSION_STATE_EXPIRED",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_ACTIVE":      1,
		"SESSION_STATE_CLOSED":      2,
		"SESSION_STATE_EXPIRED":     3,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_enumTypes[1].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_enumTypes[1]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{1}
}

type LeaseOptions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds    uint32                 `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	IdleTimeoutSeconds uint32                 `protobuf:"varint,2,opt,name=idle_timeout_seconds,json=idleTimeoutSeconds,proto3" json:"idle_timeout_seconds,omitempty"`
	MaxLifetimeSeconds uint32                 `protobuf:"varint,3,opt,name=max_lifetime_seconds,json=maxLifetimeSeconds,proto3" json:"max_lifetime_seconds,omitempty"`
	Renewable          bool                   `protobuf:"varint,4,opt,name=renewable,proto3" json:"renewable,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LeaseOptions) Reset() {
	*x = LeaseOptions{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseOptions) ProtoMessage() {}

func (x *LeaseOptions) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseOptions.ProtoReflect.Descriptor instead.
func (*LeaseOptions) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *LeaseOptions) GetDurationSeconds() uint32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *LeaseOptions) GetIdleTimeoutSeconds() uint32 {
	if x != nil {
		return x.IdleTimeoutSeconds
	}
	return 0
}

func (x *LeaseOptions) GetMaxLifetimeSeconds() uint32 {
	if x != nil {
		return x.MaxLifetimeSeconds
	}
	return 0
}

func (x *LeaseOptions) GetRenewable() bool {
	if x != nil {
		return x.Renewable
	}
	return false
}

type SessionLease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	IdleExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=idle_expires_at,json=idleExpiresAt,proto3" json:"idle_expires_at,omitempty"`
	MaxExpiresAt  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=max_expires_at,json=maxExpiresAt,proto3" json:"max_expires_at,omitempty"`
	Renewable     bool                   `protobuf:"varint,5,opt,name=renewable,proto3" json:"renewable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionLease) Reset() {
	*x = SessionLease{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionLease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionLease) ProtoMessage() {}

func (x *SessionLease) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionLease.ProtoReflect.Descriptor instead.
func (*SessionLease) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *SessionLease) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionLease) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SessionLease) GetIdleExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IdleExpiresAt
	}
	return nil
}

func (x *SessionLease) GetMaxExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MaxExpiresAt
	}
	return nil
}

func (x *SessionLease) GetRenewable() bool {
	if x != nil {
		return x.Renewable
	}
	return false
}

type ExternalRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalRef) Reset() {
	*x = ExternalRef{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalRef) ProtoMessage() {}

func (x *ExternalRef) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalRef.ProtoReflect.Descriptor instead.
func (*ExternalRef) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *ExternalRef) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ExternalRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OpenRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BackendType    string                 `protobuf:"bytes,1,opt,name=backend_type,json=backendType,proto3" json:"backend_type,omitempty"`
	BackendParams  map[string]string      `protobuf:"bytes,2,rep,name=backend_params,json=backendParams,proto3" json:"backend_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RootPath       string                 `protobuf:"bytes,3,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	Mode           AccessMode             `protobuf:"varint,4,opt,name=mode,proto3,enum=filestash.sidecar.v1.AccessMode" json:"mode,omitempty"`
	Lease          *LeaseOptions          `protobuf:"bytes,5,opt,name=lease,proto3" json:"lease,omitempty"`
	ExternalRef    *ExternalRef           `protobuf:"bytes,6,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	ClientMetadata map[string]string      `protobuf:"bytes,7,rep,name=client_metadata,json=clientMetadata,proto3" json:"client_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *OpenRequest) GetBackendType() string {
	if x != nil {
		return x.BackendType
	}
	return ""
}

func (x *OpenRequest) GetBackendParams() map[string]string {
	if x != nil {
		return x.BackendParams
	}
	return nil
}

func (x *OpenRequest) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *OpenRequest) GetMode() AccessMode {
	if x != nil {
		return x.Mode
	}
	return AccessMode_ACCESS_MODE_UNSPECIFIED
}

func (x *OpenRequest) GetLease() *LeaseOptions {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *OpenRequest) GetExternalRef() *ExternalRef {
	if x != nil {
		return x.ExternalRef
	}
	return nil
}

func (x *OpenRequest) GetClientMetadata() map[string]string {
	if x != nil {
		return x.ClientMetadata
	}
	return nil
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EffectiveMode AccessMode             `protobuf:"varint,2,opt,name=effective_mode,json=effectiveMode,proto3,enum=filestash.sidecar.v1.AccessMode" json:"effective_mode,omitempty"`
	Lease         *SessionLease          `protobuf:"bytes,3,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *OpenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OpenResponse) GetEffectiveMode() AccessMode {
	if x != nil {
		return x.EffectiveMode
	}
	return AccessMode_ACCESS_MODE_UNSPECIFIED
}

func (x *OpenResponse) GetLease() *SessionLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type CloseSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionRequest) Reset() {
	*x = CloseSessionRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionRequest) ProtoMessage() {}

func (x *CloseSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionRequest.ProtoReflect.Descriptor instead.
func (*CloseSessionRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *CloseSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ForceCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceCloseRequest) Reset() {
	*x = ForceCloseRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceCloseRequest) ProtoMessage() {}

func (x *ForceCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceCloseRequest.ProtoReflect.Descriptor instead.
func (*ForceCloseRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{6}
}

func (x *ForceCloseRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ForceCloseRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CloseSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	State         SessionState           `protobuf:"varint,2,opt,name=state,proto3,enum=filestash.sidecar.v1.SessionState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseSessionResponse) Reset() {
	*x = CloseSessionResponse{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseSessionResponse) ProtoMessage() {}

func (x *CloseSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseSessionResponse.ProtoReflect.Descriptor instead.
func (*CloseSessionResponse) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{7}
}

func (x *CloseSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CloseSessionResponse) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

type RenewSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewSessionRequest) Reset() {
	*x = RenewSessionRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewSessionRequest) ProtoMessage() {}

func (x *RenewSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewSessionRequest.ProtoReflect.Descriptor instead.
func (*RenewSessionRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{8}
}

func (x *RenewSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{9}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeClosed bool                   `protobuf:"varint,1,opt,name=include_closed,json=includeClosed,proto3" json:"include_closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsRequest) GetIncludeClosed() bool {
	if x != nil {
		return x.IncludeClosed
	}
	return false
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{11}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OwnerIdentity  string                 `protobuf:"bytes,2,opt,name=owner_identity,json=ownerIdentity,proto3" json:"owner_identity,omitempty"`
	BackendType    string                 `protobuf:"bytes,3,opt,name=backend_type,json=backendType,proto3" json:"backend_type,omitempty"`
	RedactedTarget string                 `protobuf:"bytes,4,opt,name=redacted_target,json=redactedTarget,proto3" json:"redacted_target,omitempty"`
	RootPath       string                 `protobuf:"bytes,5,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	Mode           AccessMode             `protobuf:"varint,6,opt,name=mode,proto3,enum=filestash.sidecar.v1.AccessMode" json:"mode,omitempty"`
	State          SessionState           `protobuf:"varint,7,opt,name=state,proto3,enum=filestash.sidecar.v1.SessionState" json:"state,omitempty"`
	ExternalRef    *ExternalRef           `protobuf:"bytes,8,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	OpenedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	LastUsedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	Lease          *SessionLease          `protobuf:"bytes,11,opt,name=lease,proto3" json:"lease,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{12}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetOwnerIdentity() string {
	if x != nil {
		return x.OwnerIdentity
	}
	return ""
}

func (x *SessionInfo) GetBackendType() string {
	if x != nil {
		return x.BackendType
	}
	return ""
}

func (x *SessionInfo) GetRedactedTarget() string {
	if x != nil {
		return x.RedactedTarget
	}
	return ""
}

func (x *SessionInfo) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *SessionInfo) GetMode() AccessMode {
	if x != nil {
		return x.Mode
	}
	return AccessMode_ACCESS_MODE_UNSPECIFIED
}

func (x *SessionInfo) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *SessionInfo) GetExternalRef() *ExternalRef {
	if x != nil {
		return x.ExternalRef
	}
	return nil
}

func (x *SessionInfo) GetOpenedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenedAt
	}
	return nil
}

func (x *SessionInfo) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *SessionInfo) GetLease() *SessionLease {
	if x != nil {
		return x.Lease
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTimeUnixMs int64                  `protobuf:"varint,4,opt,name=mod_time_unix_ms,json=modTimeUnixMs,proto3" json:"mod_time_unix_ms,omitempty"`
	Mode          uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{13}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetModTimeUnixMs() int64 {
	if x != nil {
		return x.ModTimeUnixMs
	}
	return 0
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{14}
}

func (x *ListRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{15}
}

func (x *ListResponse) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{16}
}

func (x *StatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileInfo              `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{17}
}

func (x *StatResponse) GetFile() *FileInfo {
	if x != nil {
		return x.File
	}
	return nil
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{18}
}

func (x *ReadFileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadFileRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadFileRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReadFileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileChunk) Reset() {
	*x = ReadFileChunk{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileChunk) ProtoMessage() {}

func (x *ReadFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileChunk.ProtoReflect.Descriptor instead.
func (*ReadFileChunk) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{19}
}

func (x *ReadFileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WriteFileRequest_Header
	//	*WriteFileRequest_Data
	Payload       isWriteFileRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{20}
}

func (x *WriteFileRequest) GetPayload() isWriteFileRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WriteFileRequest) GetHeader() *WriteFileHeader {
	if x != nil {
		if x, ok := x.Payload.(*WriteFileRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *WriteFileRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*WriteFileRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isWriteFileRequest_Payload interface {
	isWriteFileRequest_Payload()
}

type WriteFileRequest_Header struct {
	Header *WriteFileHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type WriteFileRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*WriteFileRequest_Header) isWriteFileRequest_Payload() {}

func (*WriteFileRequest_Data) isWriteFileRequest_Payload() {}

type WriteFileHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Overwrite     bool                   `protobuf:"varint,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	ExpectedSize  int64                  `protobuf:"varint,4,opt,name=expected_size,json=expectedSize,proto3" json:"expected_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileHeader) Reset() {
	*x = WriteFileHeader{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileHeader) ProtoMessage() {}

func (x *WriteFileHeader) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileHeader.ProtoReflect.Descriptor instead.
func (*WriteFileHeader) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{21}
}

func (x *WriteFileHeader) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WriteFileHeader) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileHeader) GetOverwrite() bool {
	if x != nil {
		return x.Overwrite
	}
	return false
}

func (x *WriteFileHeader) GetExpectedSize() int64 {
	if x != nil {
		return x.ExpectedSize
	}
	return 0
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesWritten  int64                  `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{22}
}

func (x *WriteFileResponse) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{23}
}

func (x *MkdirRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{25}
}

func (x *RenameRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RenameRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *RenameRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type TouchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchRequest) Reset() {
	*x = TouchRequest{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchRequest) ProtoMessage() {}

func (x *TouchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchRequest.ProtoReflect.Descriptor instead.
func (*TouchRequest) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{26}
}

func (x *TouchRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TouchRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MutationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationResponse) Reset() {
	*x = MutationResponse{}
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationResponse) ProtoMessage() {}

func (x *MutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationResponse.ProtoReflect.Descriptor instead.
func (*MutationResponse) Descriptor() ([]byte, []int) {
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP(), []int{27}
}

func (x *MutationResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_server_plugin_plg_handler_grpc_session_pb_sidecar_proto protoreflect.FileDescriptor

const file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDesc = "" +
	"\n" +
	"7server/plugin/plg_handler_grpc_session/pb/sidecar.proto\x12\x14filestash.sidecar.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\fLeaseOptions\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\rR\x0fdurationSeconds\x120\n" +
	"\x14idle_timeout_seconds\x18\x02 \x01(\rR\x12idleTimeoutSeconds\x120\n" +
	"\x14max_lifetime_seconds\x18\x03 \x01(\rR\x12maxLifetimeSeconds\x12\x1c\n" +
	"\trenewable\x18\x04 \x01(\bR\trenewable\"\x8c\x02\n" +
	"\fSessionLease\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12B\n" +
	"\x0fidle_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ridleExpiresAt\x12@\n" +
	"\x0emax_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fmaxExpiresAt\x12\x1c\n" +
	"\trenewable\x18\x05 \x01(\bR\trenewable\"1\n" +
	"\vExternalRef\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xc5\x04\n" +
	"\vOpenRequest\x12!\n" +
	"\fbackend_type\x18\x01 \x01(\tR\vbackendType\x12[\n" +
	"\x0ebackend_params\x18\x02 \x03(\v24.filestash.sidecar.v1.OpenRequest.BackendParamsEntryR\rbackendParams\x12\x1b\n" +
	"\troot_path\x18\x03 \x01(\tR\brootPath\x124\n" +
	"\x04mode\x18\x04 \x01(\x0e2 .filestash.sidecar.v1.AccessModeR\x04mode\x128\n" +
	"\x05lease\x18\x05 \x01(\v2\".filestash.sidecar.v1.LeaseOptionsR\x05lease\x12D\n" +
	"\fexternal_ref\x18\x06 \x01(\v2!.filestash.sidecar.v1.ExternalRefR\vexternalRef\x12^\n" +
	"\x0fclient_metadata\x18\a \x03(\v25.filestash.sidecar.v1.OpenRequest.ClientMetadataEntryR\x0eclientMetadata\x1a@\n" +
	"\x12BackendParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13ClientMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb0\x01\n" +
	"\fOpenResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12G\n" +
	"\x0eeffective_mode\x18\x02 \x01(\x0e2 .filestash.sidecar.v1.AccessModeR\reffectiveMode\x128\n" +
	"\x05lease\x18\x03 \x01(\v2\".filestash.sidecar.v1.SessionLeaseR\x05lease\"4\n" +
	"\x13CloseSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"J\n" +
	"\x11ForceCloseRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"o\n" +
	"\x14CloseSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x128\n" +
	"\x05state\x18\x02 \x01(\x0e2\".filestash.sidecar.v1.SessionStateR\x05state\"4\n" +
	"\x13RenewSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"<\n" +
	"\x13ListSessionsRequest\x12%\n" +
	"\x0einclude_closed\x18\x01 \x01(\bR\rincludeClosed\"U\n" +
	"\x14ListSessionsResponse\x12=\n" +
	"\bsessions\x18\x01 \x03(\v2!.filestash.sidecar.v1.SessionInfoR\bsessions\"\xa3\x04\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0eowner_identity\x18\x02 \x01(\tR\rownerIdentity\x12!\n" +
	"\fbackend_type\x18\x03 \x01(\tR\vbackendType\x12'\n" +
	"\x0fredacted_target\x18\x04 \x01(\tR\x0eredactedTarget\x12\x1b\n" +
	"\troot_path\x18\x05 \x01(\tR\brootPath\x124\n" +
	"\x04mode\x18\x06 \x01(\x0e2 .filestash.sidecar.v1.AccessModeR\x04mode\x128\n" +
	"\x05state\x18\a \x01(\x0e2\".filestash.sidecar.v1.SessionStateR\x05state\x12D\n" +
	"\fexternal_ref\x18\b \x01(\v2!.filestash.sidecar.v1.ExternalRefR\vexternalRef\x127\n" +
	"\topened_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bopenedAt\x12<\n" +
	"\flast_used_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x128\n" +
	"\x05lease\x18\v \x01(\v2\".filestash.sidecar.v1.SessionLeaseR\x05lease\"\x83\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12'\n" +
	"\x10mod_time_unix_ms\x18\x04 \x01(\x03R\rmodTimeUnixMs\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\"@\n" +
	"\vListRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"D\n" +
	"\fListResponse\x124\n" +
	"\x05files\x18\x01 \x03(\v2\x1e.filestash.sidecar.v1.FileInfoR\x05files\"@\n" +
	"\vStatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"B\n" +
	"\fStatResponse\x122\n" +
	"\x04file\x18\x01 \x01(\v2\x1e.filestash.sidecar.v1.FileInfoR\x04file\"r\n" +
	"\x0fReadFileRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\"#\n" +
	"\rReadFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"t\n" +
	"\x10WriteFileRequest\x12?\n" +
	"\x06header\x18\x01 \x01(\v2%.filestash.sidecar.v1.WriteFileHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\x87\x01\n" +
	"\x0fWriteFileHeader\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1c\n" +
	"\toverwrite\x18\x03 \x01(\bR\toverwrite\x12#\n" +
	"\rexpected_size\x18\x04 \x01(\x03R\fexpectedSize\"8\n" +
	"\x11WriteFileResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\x03R\fbytesWritten\"A\n" +
	"\fMkdirRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"B\n" +
	"\rRemoveRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"R\n" +
	"\rRenameRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\"A\n" +
	"\fTouchRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\"\n" +
	"\x10MutationResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*[\n" +
	"\n" +
	"AccessMode\x12\x1b\n" +
	"\x17ACCESS_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ACCESS_MODE_READ\x10\x01\x12\x1a\n" +
	"\x16ACCESS_MODE_READ_WRITE\x10\x02*|\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SESSION_STATE_ACTIVE\x10\x01\x12\x18\n" +
	"\x14SESSION_STATE_CLOSED\x10\x02\x12\x19\n" +
	"\x15SESSION_STATE_EXPIRED\x10\x032\xfb\t\n" +
	"\x17FilestashSidecarService\x12M\n" +
	"\x04Open\x12!.filestash.sidecar.v1.OpenRequest\x1a\".filestash.sidecar.v1.OpenResponse\x12^\n" +
	"\x05Close\x12).filestash.sidecar.v1.CloseSessionRequest\x1a*.filestash.sidecar.v1.CloseSessionResponse\x12]\n" +
	"\fRenewSession\x12).filestash.sidecar.v1.RenewSessionRequest\x1a\".filestash.sidecar.v1.SessionLease\x12X\n" +
	"\n" +
	"GetSession\x12'.filestash.sidecar.v1.GetSessionRequest\x1a!.filestash.sidecar.v1.SessionInfo\x12e\n" +
	"\fListSessions\x12).filestash.sidecar.v1.ListSessionsRequest\x1a*.filestash.sidecar.v1.ListSessionsResponse\x12a\n" +
	"\n" +
	"ForceClose\x12'.filestash.sidecar.v1.ForceCloseRequest\x1a*.filestash.sidecar.v1.CloseSessionResponse\x12M\n" +
	"\x04List\x12!.filestash.sidecar.v1.ListRequest\x1a\".filestash.sidecar.v1.ListResponse\x12M\n" +
	"\x04Stat\x12!.filestash.sidecar.v1.StatRequest\x1a\".filestash.sidecar.v1.StatResponse\x12X\n" +
	"\bReadFile\x12%.filestash.sidecar.v1.ReadFileRequest\x1a#.filestash.sidecar.v1.ReadFileChunk0\x01\x12^\n" +
	"\tWriteFile\x12&.filestash.sidecar.v1.WriteFileRequest\x1a'.filestash.sidecar.v1.WriteFileResponse(\x01\x12S\n" +
	"\x05Mkdir\x12\".filestash.sidecar.v1.MkdirRequest\x1a&.filestash.sidecar.v1.MutationResponse\x12U\n" +
	"\x06Remove\x12#.filestash.sidecar.v1.RemoveRequest\x1a&.filestash.sidecar.v1.MutationResponse\x12U\n" +
	"\x06Rename\x12#.filestash.sidecar.v1.RenameRequest\x1a&.filestash.sidecar.v1.MutationResponse\x12S\n" +
	"\x05Touch\x12\".filestash.sidecar.v1.TouchRequest\x1a&.filestash.sidecar.v1.MutationResponseBSZQgithub.com/mickael-kerjean/filestash/server/plugin/plg_handler_grpc_session/pb;pbb\x06proto3"

var (
	file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescOnce sync.Once
	file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescData []byte
)

func file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescGZIP() []byte {
	file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescOnce.Do(func() {
		file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDesc), len(file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDesc)))
	})
	return file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDescData
}

var file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_goTypes = []any{
	(AccessMode)(0),               // 0: filestash.sidecar.v1.AccessMode
	(SessionState)(0),             // 1: filestash.sidecar.v1.SessionState
	(*LeaseOptions)(nil),          // 2: filestash.sidecar.v1.LeaseOptions
	(*SessionLease)(nil),          // 3: filestash.sidecar.v1.SessionLease
	(*ExternalRef)(nil),           // 4: filestash.sidecar.v1.ExternalRef
	(*OpenRequest)(nil),           // 5: filestash.sidecar.v1.OpenRequest
	(*OpenResponse)(nil),          // 6: filestash.sidecar.v1.OpenResponse
	(*CloseSessionRequest)(nil),   // 7: filestash.sidecar.v1.CloseSessionRequest
	(*ForceCloseRequest)(nil),     // 8: filestash.sidecar.v1.ForceCloseRequest
	(*CloseSessionResponse)(nil),  // 9: filestash.sidecar.v1.CloseSessionResponse
	(*RenewSessionRequest)(nil),   // 10: filestash.sidecar.v1.RenewSessionRequest
	(*GetSessionRequest)(nil),     // 11: filestash.sidecar.v1.GetSessionRequest
	(*ListSessionsRequest)(nil),   // 12: filestash.sidecar.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),  // 13: filestash.sidecar.v1.ListSessionsResponse
	(*SessionInfo)(nil),           // 14: filestash.sidecar.v1.SessionInfo
	(*FileInfo)(nil),              // 15: filestash.sidecar.v1.FileInfo
	(*ListRequest)(nil),           // 16: filestash.sidecar.v1.ListRequest
	(*ListResponse)(nil),          // 17: filestash.sidecar.v1.ListResponse
	(*StatRequest)(nil),           // 18: filestash.sidecar.v1.StatRequest
	(*StatResponse)(nil),          // 19: filestash.sidecar.v1.StatResponse
	(*ReadFileRequest)(nil),       // 20: filestash.sidecar.v1.ReadFileRequest
	(*ReadFileChunk)(nil),         // 21: filestash.sidecar.v1.ReadFileChunk
	(*WriteFileRequest)(nil),      // 22: filestash.sidecar.v1.WriteFileRequest
	(*WriteFileHeader)(nil),       // 23: filestash.sidecar.v1.WriteFileHeader
	(*WriteFileResponse)(nil),     // 24: filestash.sidecar.v1.WriteFileResponse
	(*MkdirRequest)(nil),          // 25: filestash.sidecar.v1.MkdirRequest
	(*RemoveRequest)(nil),         // 26: filestash.sidecar.v1.RemoveRequest
	(*RenameRequest)(nil),         // 27: filestash.sidecar.v1.RenameRequest
	(*TouchRequest)(nil),          // 28: filestash.sidecar.v1.TouchRequest
	(*MutationResponse)(nil),      // 29: filestash.sidecar.v1.MutationResponse
	nil,                           // 30: filestash.sidecar.v1.OpenRequest.BackendParamsEntry
	nil,                           // 31: filestash.sidecar.v1.OpenRequest.ClientMetadataEntry
	(*timestamppb.Timestamp)(nil), // 32: google.protobuf.Timestamp
}
var file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_depIdxs = []int32{
	32, // 0: filestash.sidecar.v1.SessionLease.expires_at:type_name -> google.protobuf.Timestamp
	32, // 1: filestash.sidecar.v1.SessionLease.idle_expires_at:type_name -> google.protobuf.Timestamp
	32, // 2: filestash.sidecar.v1.SessionLease.max_expires_at:type_name -> google.protobuf.Timestamp
	30, // 3: filestash.sidecar.v1.OpenRequest.backend_params:type_name -> filestash.sidecar.v1.OpenRequest.BackendParamsEntry
	0,  // 4: filestash.sidecar.v1.OpenRequest.mode:type_name -> filestash.sidecar.v1.AccessMode
	2,  // 5: filestash.sidecar.v1.OpenRequest.lease:type_name -> filestash.sidecar.v1.LeaseOptions
	4,  // 6: filestash.sidecar.v1.OpenRequest.external_ref:type_name -> filestash.sidecar.v1.ExternalRef
	31, // 7: filestash.sidecar.v1.OpenRequest.client_metadata:type_name -> filestash.sidecar.v1.OpenRequest.ClientMetadataEntry
	0,  // 8: filestash.sidecar.v1.OpenResponse.effective_mode:type_name -> filestash.sidecar.v1.AccessMode
	3,  // 9: filestash.sidecar.v1.OpenResponse.lease:type_name -> filestash.sidecar.v1.SessionLease
	1,  // 10: filestash.sidecar.v1.CloseSessionResponse.state:type_name -> filestash.sidecar.v1.SessionState
	14, // 11: filestash.sidecar.v1.ListSessionsResponse.sessions:type_name -> filestash.sidecar.v1.SessionInfo
	0,  // 12: filestash.sidecar.v1.SessionInfo.mode:type_name -> filestash.sidecar.v1.AccessMode
	1,  // 13: filestash.sidecar.v1.SessionInfo.state:type_name -> filestash.sidecar.v1.SessionState
	4,  // 14: filestash.sidecar.v1.SessionInfo.external_ref:type_name -> filestash.sidecar.v1.ExternalRef
	32, // 15: filestash.sidecar.v1.SessionInfo.opened_at:type_name -> google.protobuf.Timestamp
	32, // 16: filestash.sidecar.v1.SessionInfo.last_used_at:type_name -> google.protobuf.Timestamp
	3,  // 17: filestash.sidecar.v1.SessionInfo.lease:type_name -> filestash.sidecar.v1.SessionLease
	15, // 18: filestash.sidecar.v1.ListResponse.files:type_name -> filestash.sidecar.v1.FileInfo
	15, // 19: filestash.sidecar.v1.StatResponse.file:type_name -> filestash.sidecar.v1.FileInfo
	23, // 20: filestash.sidecar.v1.WriteFileRequest.header:type_name -> filestash.sidecar.v1.WriteFileHeader
	5,  // 21: filestash.sidecar.v1.FilestashSidecarService.Open:input_type -> filestash.sidecar.v1.OpenRequest
	7,  // 22: filestash.sidecar.v1.FilestashSidecarService.Close:input_type -> filestash.sidecar.v1.CloseSessionRequest
	10, // 23: filestash.sidecar.v1.FilestashSidecarService.RenewSession:input_type -> filestash.sidecar.v1.RenewSessionRequest
	11, // 24: filestash.sidecar.v1.FilestashSidecarService.GetSession:input_type -> filestash.sidecar.v1.GetSessionRequest
	12, // 25: filestash.sidecar.v1.FilestashSidecarService.ListSessions:input_type -> filestash.sidecar.v1.ListSessionsRequest
	8,  // 26: filestash.sidecar.v1.FilestashSidecarService.ForceClose:input_type -> filestash.sidecar.v1.ForceCloseRequest
	16, // 27: filestash.sidecar.v1.FilestashSidecarService.List:input_type -> filestash.sidecar.v1.ListRequest
	18, // 28: filestash.sidecar.v1.FilestashSidecarService.Stat:input_type -> filestash.sidecar.v1.StatRequest
	20, // 29: filestash.sidecar.v1.FilestashSidecarService.ReadFile:input_type -> filestash.sidecar.v1.ReadFileRequest
	22, // 30: filestash.sidecar.v1.FilestashSidecarService.WriteFile:input_type -> filestash.sidecar.v1.WriteFileRequest
	25, // 31: filestash.sidecar.v1.FilestashSidecarService.Mkdir:input_type -> filestash.sidecar.v1.MkdirRequest
	26, // 32: filestash.sidecar.v1.FilestashSidecarService.Remove:input_type -> filestash.sidecar.v1.RemoveRequest
	27, // 33: filestash.sidecar.v1.FilestashSidecarService.Rename:input_type -> filestash.sidecar.v1.RenameRequest
	28, // 34: filestash.sidecar.v1.FilestashSidecarService.Touch:input_type -> filestash.sidecar.v1.TouchRequest
	6,  // 35: filestash.sidecar.v1.FilestashSidecarService.Open:output_type -> filestash.sidecar.v1.OpenResponse
	9,  // 36: filestash.sidecar.v1.FilestashSidecarService.Close:output_type -> filestash.sidecar.v1.CloseSessionResponse
	3,  // 37: filestash.sidecar.v1.FilestashSidecarService.RenewSession:output_type -> filestash.sidecar.v1.SessionLease
	14, // 38: filestash.sidecar.v1.FilestashSidecarService.GetSession:output_type -> filestash.sidecar.v1.SessionInfo
	13, // 39: filestash.sidecar.v1.FilestashSidecarService.ListSessions:output_type -> filestash.sidecar.v1.ListSessionsResponse
	9,  // 40: filestash.sidecar.v1.FilestashSidecarService.ForceClose:output_type -> filestash.sidecar.v1.CloseSessionResponse
	17, // 41: filestash.sidecar.v1.FilestashSidecarService.List:output_type -> filestash.sidecar.v1.ListResponse
	19, // 42: filestash.sidecar.v1.FilestashSidecarService.Stat:output_type -> filestash.sidecar.v1.StatResponse
	21, // 43: filestash.sidecar.v1.FilestashSidecarService.ReadFile:output_type -> filestash.sidecar.v1.ReadFileChunk
	24, // 44: filestash.sidecar.v1.FilestashSidecarService.WriteFile:output_type -> filestash.sidecar.v1.WriteFileResponse
	29, // 45: filestash.sidecar.v1.FilestashSidecarService.Mkdir:output_type -> filestash.sidecar.v1.MutationResponse
	29, // 46: filestash.sidecar.v1.FilestashSidecarService.Remove:output_type -> filestash.sidecar.v1.MutationResponse
	29, // 47: filestash.sidecar.v1.FilestashSidecarService.Rename:output_type -> filestash.sidecar.v1.MutationResponse
	29, // 48: filestash.sidecar.v1.FilestashSidecarService.Touch:output_type -> filestash.sidecar.v1.MutationResponse
	35, // [35:49] is the sub-list for method output_type
	21, // [21:35] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_init() }
func file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_init() {
	if File_server_plugin_plg_handler_grpc_session_pb_sidecar_proto != nil {
		return
	}
	file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes[20].OneofWrappers = []any{
		(*WriteFileRequest_Header)(nil),
		(*WriteFileRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDesc), len(file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_goTypes,
		DependencyIndexes: file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_depIdxs,
		EnumInfos:         file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_enumTypes,
		MessageInfos:      file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_msgTypes,
	}.Build()
	File_server_plugin_plg_handler_grpc_session_pb_sidecar_proto = out.File
	file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_goTypes = nil
	file_server_plugin_plg_handler_grpc_session_pb_sidecar_proto_depIdxs = nil
}
