// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: server/plugin/plg_handler_grpc_session/pb/sidecar.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FilestashSidecarService_Open_FullMethodName         = "/filestash.sidecar.v1.FilestashSidecarService/Open"
	FilestashSidecarService_Close_FullMethodName        = "/filestash.sidecar.v1.FilestashSidecarService/Close"
	FilestashSidecarService_RenewSession_FullMethodName = "/filestash.sidecar.v1.FilestashSidecarService/RenewSession"
	FilestashSidecarService_GetSession_FullMethodName   = "/filestash.sidecar.v1.FilestashSidecarService/GetSession"
	FilestashSidecarService_ListSessions_FullMethodName = "/filestash.sidecar.v1.FilestashSidecarService/ListSessions"
	FilestashSidecarService_ForceClose_FullMethodName   = "/filestash.sidecar.v1.FilestashSidecarService/ForceClose"
	FilestashSidecarService_List_FullMethodName         = "/filestash.sidecar.v1.FilestashSidecarService/List"
	FilestashSidecarService_Stat_FullMethodName         = "/filestash.sidecar.v1.FilestashSidecarService/Stat"
	FilestashSidecarService_ReadFile_FullMethodName     = "/filestash.sidecar.v1.FilestashSidecarService/ReadFile"
	FilestashSidecarService_WriteFile_FullMethodName    = "/filestash.sidecar.v1.FilestashSidecarService/WriteFile"
	FilestashSidecarService_Mkdir_FullMethodName        = "/filestash.sidecar.v1.FilestashSidecarService/Mkdir"
	FilestashSidecarService_Remove_FullMethodName       = "/filestash.sidecar.v1.FilestashSidecarService/Remove"
	FilestashSidecarService_Rename_FullMethodName       = "/filestash.sidecar.v1.FilestashSidecarService/Rename"
	FilestashSidecarService_Touch_FullMethodName        = "/filestash.sidecar.v1.FilestashSidecarService/Touch"
)

// FilestashSidecarServiceClient is the client API for FilestashSidecarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilestashSidecarServiceClient interface {
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	Close(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
	RenewSession(ctx context.Context, in *RenewSessionRequest, opts ...grpc.CallOption) (*SessionLease, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionInfo, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	ForceClose(ctx context.Context, in *ForceCloseRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFileChunk], error)
	WriteFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileRequest, WriteFileResponse], error)
	Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MutationResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*MutationResponse, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*MutationResponse, error)
	Touch(ctx context.Context, in *TouchRequest, opts ...grpc.CallOption) (*MutationResponse, error)
}

type filestashSidecarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilestashSidecarServiceClient(cc grpc.ClientConnInterface) FilestashSidecarServiceClient {
	return &filestashSidecarServiceClient{cc}
}

func (c *filestashSidecarServiceClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, FilestashSidecarService_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filestashSidecarServiceClient) Close(ctx context.Context, in *CloseSessionRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, FilestashSidecarService_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filestashSidecarServiceClient) RenewSession(ctx context.Context, in *RenewSessionRequest, opts ...grpc.CallOption) (*SessionLease, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionLease)
	err := c.cc.Invoke(ctx, FilestashSidecarService_RenewSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filestashSidecarServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*SessionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, FilestashSidecarService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filestashSidecarServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, FilestashSidecarService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filestashSidecarServiceClient) ForceClose(ctx context.Context, in *ForceCloseRequest, opts ...grpc.CallOption) (*CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseSessionResponse)
	err := c.cc.Invoke(ctx, FilestashSidecarService_ForceClose_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filestashSidecarServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, FilestashSidecarService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filestashSidecarServiceClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, FilestashSidecarService_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filestashSidecarServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FilestashSidecarService_ServiceDesc.Streams[0], FilestashSidecarService_ReadFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadFileRequest, ReadFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FilestashSidecarService_ReadFileClient = grpc.ServerStreamingClient[ReadFileChunk]

func (c *filestashSidecarServiceClient) WriteFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFileRequest, WriteFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FilestashSidecarService_ServiceDesc.Streams[1], FilestashSidecarService_WriteFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFileRequest, WriteFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FilestashSidecarService_WriteFileClient = grpc.ClientStreamingClient[WriteFileRequest, WriteFileResponse]

func (c *filestashSidecarServiceClient) Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResponse)
	err := c.cc.Invoke(ctx, FilestashSidecarService_Mkdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filestashSidecarServiceClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*MutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResponse)
	err := c.cc.Invoke(ctx, FilestashSidecarService_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filestashSidecarServiceClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*MutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResponse)
	err := c.cc.Invoke(ctx, FilestashSidecarService_Rename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filestashSidecarServiceClient) Touch(ctx context.Context, in *TouchRequest, opts ...grpc.CallOption) (*MutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutationResponse)
	err := c.cc.Invoke(ctx, FilestashSidecarService_Touch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilestashSidecarServiceServer is the server API for FilestashSidecarService service.
// All implementations must embed UnimplementedFilestashSidecarServiceServer
// for forward compatibility.
type FilestashSidecarServiceServer interface {
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	Close(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error)
	RenewSession(context.Context, *RenewSessionRequest) (*SessionLease, error)
	GetSession(context.Context, *GetSessionRequest) (*SessionInfo, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	ForceClose(context.Context, *ForceCloseRequest) (*CloseSessionResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[ReadFileChunk]) error
	WriteFile(grpc.ClientStreamingServer[WriteFileRequest, WriteFileResponse]) error
	Mkdir(context.Context, *MkdirRequest) (*MutationResponse, error)
	Remove(context.Context, *RemoveRequest) (*MutationResponse, error)
	Rename(context.Context, *RenameRequest) (*MutationResponse, error)
	Touch(context.Context, *TouchRequest) (*MutationResponse, error)
	mustEmbedUnimplementedFilestashSidecarServiceServer()
}

// UnimplementedFilestashSidecarServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFilestashSidecarServiceServer struct{}

func (UnimplementedFilestashSidecarServiceServer) Open(context.Context, *OpenRequest) (*OpenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) Close(context.Context, *CloseSessionRequest) (*CloseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) RenewSession(context.Context, *RenewSessionRequest) (*SessionLease, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewSession not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) GetSession(context.Context, *GetSessionRequest) (*SessionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) ForceClose(context.Context, *ForceCloseRequest) (*CloseSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceClose not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) ReadFile(*ReadFileRequest, grpc.ServerStreamingServer[ReadFileChunk]) error {
	return status.Error(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) WriteFile(grpc.ClientStreamingServer[WriteFileRequest, WriteFileResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) Mkdir(context.Context, *MkdirRequest) (*MutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mkdir not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) Remove(context.Context, *RemoveRequest) (*MutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) Rename(context.Context, *RenameRequest) (*MutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) Touch(context.Context, *TouchRequest) (*MutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Touch not implemented")
}
func (UnimplementedFilestashSidecarServiceServer) mustEmbedUnimplementedFilestashSidecarServiceServer() {
}
func (UnimplementedFilestashSidecarServiceServer) testEmbeddedByValue() {}

// UnsafeFilestashSidecarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilestashSidecarServiceServer will
// result in compilation errors.
type UnsafeFilestashSidecarServiceServer interface {
	mustEmbedUnimplementedFilestashSidecarServiceServer()
}

func RegisterFilestashSidecarServiceServer(s grpc.ServiceRegistrar, srv FilestashSidecarServiceServer) {
	// If the following call panics, it indicates UnimplementedFilestashSidecarServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FilestashSidecarService_ServiceDesc, srv)
}

func _FilestashSidecarService_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilestashSidecarServiceServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilestashSidecarService_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilestashSidecarServiceServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilestashSidecarService_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilestashSidecarServiceServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilestashSidecarService_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilestashSidecarServiceServer).Close(ctx, req.(*CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilestashSidecarService_RenewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilestashSidecarServiceServer).RenewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilestashSidecarService_RenewSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilestashSidecarServiceServer).RenewSession(ctx, req.(*RenewSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilestashSidecarService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilestashSidecarServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilestashSidecarService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilestashSidecarServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilestashSidecarService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilestashSidecarServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilestashSidecarService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilestashSidecarServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilestashSidecarService_ForceClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceCloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilestashSidecarServiceServer).ForceClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilestashSidecarService_ForceClose_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilestashSidecarServiceServer).ForceClose(ctx, req.(*ForceCloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilestashSidecarService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilestashSidecarServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilestashSidecarService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilestashSidecarServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilestashSidecarService_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilestashSidecarServiceServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilestashSidecarService_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilestashSidecarServiceServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilestashSidecarService_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FilestashSidecarServiceServer).ReadFile(m, &grpc.GenericServerStream[ReadFileRequest, ReadFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FilestashSidecarService_ReadFileServer = grpc.ServerStreamingServer[ReadFileChunk]

func _FilestashSidecarService_WriteFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FilestashSidecarServiceServer).WriteFile(&grpc.GenericServerStream[WriteFileRequest, WriteFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FilestashSidecarService_WriteFileServer = grpc.ClientStreamingServer[WriteFileRequest, WriteFileResponse]

func _FilestashSidecarService_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilestashSidecarServiceServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilestashSidecarService_Mkdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilestashSidecarServiceServer).Mkdir(ctx, req.(*MkdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilestashSidecarService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilestashSidecarServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilestashSidecarService_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilestashSidecarServiceServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilestashSidecarService_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilestashSidecarServiceServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilestashSidecarService_Rename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilestashSidecarServiceServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilestashSidecarService_Touch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilestashSidecarServiceServer).Touch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilestashSidecarService_Touch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilestashSidecarServiceServer).Touch(ctx, req.(*TouchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilestashSidecarService_ServiceDesc is the grpc.ServiceDesc for FilestashSidecarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilestashSidecarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filestash.sidecar.v1.FilestashSidecarService",
	HandlerType: (*FilestashSidecarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _FilestashSidecarService_Open_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _FilestashSidecarService_Close_Handler,
		},
		{
			MethodName: "RenewSession",
			Handler:    _FilestashSidecarService_RenewSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _FilestashSidecarService_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _FilestashSidecarService_ListSessions_Handler,
		},
		{
			MethodName: "ForceClose",
			Handler:    _FilestashSidecarService_ForceClose_Handler,
		},
		{
			MethodName: "List",
			Handler:    _FilestashSidecarService_List_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _FilestashSidecarService_Stat_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _FilestashSidecarService_Mkdir_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _FilestashSidecarService_Remove_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _FilestashSidecarService_Rename_Handler,
		},
		{
			MethodName: "Touch",
			Handler:    _FilestashSidecarService_Touch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadFile",
			Handler:       _FilestashSidecarService_ReadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteFile",
			Handler:       _FilestashSidecarService_WriteFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "server/plugin/plg_handler_grpc_session/pb/sidecar.proto",
}
